version: 0.0
os: linux
files:
  - source: /server
    destination: /home/ec2-user/myrepo
hooks:
# Install:
  AfterInstall:
    - location: server/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: server/application_start.sh
      timeout: 300
      runas: root
# ValidateService:
